# Pytorch Fundamental
## 1. Matrices
### Matrices Brief Introduction
* Basic definition: rectangular array of numbers.
* Ndarrays(NumPy)
* Tensors (PyTorch)

### 1.1 Creating Matrices
Import Numpy and pytorch

In [1]:
import numpy as np 
import torch

Creating Nested List

In [2]:
arr = [[1, 2], [3, 4]]
print(type(arr))
arr

<class 'list'>


[[1, 2], [3, 4]]

Creating a 2x2 array using NumPy

In [3]:
# Convert to numpy array
np_arr = np.array(arr)
print(type(np_arr))
np_arr

<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

Create 2x2 Tensor using torch

In [4]:
# Convert to Pytorch Tensor
tch_arr = torch.tensor(arr)
print(type(tch_arr))
tch_arr

<class 'torch.Tensor'>


tensor([[1, 2],
        [3, 4]])

___
### 1.2 Create Matrices with Default Values
#### One Value
**Using Numpy**

In [5]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

**Using Torch**

In [6]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

#### Random Value
**Using Numpy**

In [7]:
np.random.rand(2, 2)

array([[0.41049675, 0.60221437],
       [0.55320088, 0.07178488]])

**Using Torch**

In [8]:
torch.rand(2, 2)

tensor([[0.4692, 0.7640],
        [0.2026, 0.8999]])

___
### 1.3 Seeds for Reproducibility
**Using Numpy**

In [9]:
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

**Using Torch**

In [10]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

**Torch GPU**

In [11]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [12]:
torch.cuda.is_available()

False

___
### 1.4 Numpy and Torch Bridge
### 1.4.1 Numpy to Torch

In [13]:
np_array = np.ones((2, 2))
print(type(np_array))
np_array

<class 'numpy.ndarray'>


array([[1., 1.],
       [1., 1.]])

**Convert to Torch Tensor**

In [14]:
torch_tensor = torch.from_numpy(np_array)
print(type(torch_tensor))
torch_tensor

<class 'torch.Tensor'>


tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

### Data types matter: Torch version `1.1.0` now is automatically update the data type

In [15]:
print("Torch version is : ",torch.__version__)

Torch version is :  1.1.0


In [16]:
np_array_int = np.ones((2, 2), dtype=np.int8)
print(type(np_array_int))
np_array_int

<class 'numpy.ndarray'>


array([[1, 1],
       [1, 1]], dtype=int8)

**Now, we convert to Torch Tensor**

In [17]:
torch_tensor_int = torch.from_numpy(np_array_int)
print(type(torch_tensor_int))
torch_tensor_int

<class 'torch.Tensor'>


tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

___
### 1.4.2 Torch to Numpy

In [18]:
torch_tensor = torch.ones(2, 2)
print(type(torch_tensor))
torch_tensor

<class 'torch.Tensor'>


tensor([[1., 1.],
        [1., 1.]])

**Convert to Numpy**


In [19]:
torch_to_numpy = torch_tensor.numpy()
print(type(torch_to_numpy))
torch_to_numpy

<class 'numpy.ndarray'>


array([[1., 1.],
       [1., 1.]], dtype=float32)

### 1.4.3 Tensor on CPU vs GPU
**Create CPU Tensor**

In [20]:
tensor_cpu = torch.ones(2, 2)
print(type(tensor_cpu))
tensor_cpu

<class 'torch.Tensor'>


tensor([[1., 1.],
        [1., 1.]])

**Convert CPU Tensor to Tensor GPU**

In [21]:
if torch.cuda.is_available():
    tensor_cuda = tensor_cpu.cuda()

print("Is GPU Available : ",torch.cuda.is_available())

Is GPU Available :  False


**Convert Tensor GPU to Tensor CPU**

In [22]:
if torch.cuda.is_available():
    tensor_cpu_convert = tensor_cuda.cpu()

___
### 1.5 Tensor Operation


In [23]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

**Show Tensor Size**

In [24]:
# Method 1
ones.shape

torch.Size([2, 3])

In [25]:
# Method 2
ones.size()

torch.Size([2, 3])

### 1.5.1 Resizing/Reshaping Tensor

**Resize to 6 Column**

In [26]:
ones_6 = ones.view(6)
print(ones_6.shape)
ones_6

torch.Size([6])


tensor([1., 1., 1., 1., 1., 1.])

**Resize to 6 Row**

In [27]:
ones_6_1 = ones.view(6, 1)
print(ones_6_1.shape)
ones_6_1

torch.Size([6, 1])


tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

**Resize to (3,2)**

In [28]:
ones_3_2 = ones.view(3, 2)
print(ones_3_2.shape)
ones_3_2

torch.Size([3, 2])


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

**Resize to (2, 3, 1)**

In [29]:
ones_2_3_1 = ones.view(2, 3, 1)
print(ones_2_3_1.shape)
ones_2_3_1

torch.Size([2, 3, 1])


tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])

___
### 1.5.2 Element-wise Addition

In [30]:
ones = torch.ones(2, 2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [31]:
twos = ones + 2
twos

tensor([[3., 3.],
        [3., 3.]])

In [32]:
# Method 1
plus = ones + twos
plus

tensor([[4., 4.],
        [4., 4.]])

In [33]:
# Method 2
plus = torch.add(ones, twos)
plus

tensor([[4., 4.],
        [4., 4.]])

**In-place Operations**

Usually, inplace operation using function with `_` (underscore)

In [34]:
plus

tensor([[4., 4.],
        [4., 4.]])

In [35]:
# Method 3
plus.add(twos)

tensor([[7., 7.],
        [7., 7.]])

In [36]:
plus

tensor([[4., 4.],
        [4., 4.]])

Now, we use inplace addition

In [37]:
plus.add_(twos)

tensor([[7., 7.],
        [7., 7.]])

In [38]:
plus

tensor([[7., 7.],
        [7., 7.]])

___
### 1.5.3 Element-wise  Substraction

In [39]:
print(ones)
print(twos)

tensor([[1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.]])


In [40]:
# Method 1
minus = twos - ones
minus

tensor([[2., 2.],
        [2., 2.]])

In [41]:
# Method 2
minus = torch.sub(twos, ones)
minus

tensor([[2., 2.],
        [2., 2.]])

**Not In-place substraction**

In [42]:
minus

tensor([[2., 2.],
        [2., 2.]])

In [43]:
minus.sub(ones)

tensor([[1., 1.],
        [1., 1.]])

In [44]:
minus

tensor([[2., 2.],
        [2., 2.]])

**In-place Substraction**

In [45]:
minus.sub_(ones)

tensor([[1., 1.],
        [1., 1.]])

In [46]:
minus

tensor([[1., 1.],
        [1., 1.]])

___
### 1.5.4 Element-wise Multiplication

In [47]:
torch_a = torch.tensor([[2, 2], [2, 2]])
torch_b = torch.tensor([[4, 4], [4, 4]])

print(torch_a, '\n\n', torch_b)

tensor([[2, 2],
        [2, 2]]) 

 tensor([[4, 4],
        [4, 4]])


In [48]:
# Method 1
torch_a * torch_b

tensor([[8, 8],
        [8, 8]])

In [49]:
# Method 2
torch.mul(torch_a, torch_b)

tensor([[8, 8],
        [8, 8]])

**Not In-place Multiplication**

In [50]:
torch_a

tensor([[2, 2],
        [2, 2]])

In [51]:
# Method 3
torch_a.mul(torch_b)

tensor([[8, 8],
        [8, 8]])

In [52]:
torch_a

tensor([[2, 2],
        [2, 2]])

**In-place multiplication**

In [53]:
torch_a.mul_(torch_b)

tensor([[8, 8],
        [8, 8]])

In [54]:
torch_a

tensor([[8, 8],
        [8, 8]])

___
### 1.5.5 Matrix Multiplication (Dot Product)
```
a = [[2, 2], 
     [2, 2]]

b = [[4, 4],
     [4, 4]]

```
Matric Multiplication :
```
matmul = [[(2*4 + 2*4), (2*4 + 2*4)],
          [(2*4 + 2*4), (2*4 + 2*4)]]
```

In [55]:
torch_a = torch.tensor([[2, 2], [2, 2]])
torch_b = torch.tensor([[4, 4], [4, 4]])

print(torch_a, '\n\n', torch_b)

tensor([[2, 2],
        [2, 2]]) 

 tensor([[4, 4],
        [4, 4]])


In [56]:
# Method 1
torch.matmul(torch_a, torch_b)

tensor([[16, 16],
        [16, 16]])

In [57]:
# Method 2
torch.mm(torch_a,torch_b)

tensor([[16, 16],
        [16, 16]])

In [58]:
# Method 3
torch_a.matmul(torch_b)

tensor([[16, 16],
        [16, 16]])

In [59]:
# Method 4
torch_a.mm(torch_b)

tensor([[16, 16],
        [16, 16]])

___
### 1.5.6 Element-wise Division

In [60]:
torch_a = torch.tensor([[8, 8], [8, 8]])
torch_b = torch.tensor([[4, 4], [4, 4]])

print(torch_a, '\n\n', torch_b)

tensor([[8, 8],
        [8, 8]]) 

 tensor([[4, 4],
        [4, 4]])


In [61]:
# Method 1
torch_a / torch_b

tensor([[2, 2],
        [2, 2]])

In [62]:
# Method 2
torch.div(torch_a, torch_b)

tensor([[2, 2],
        [2, 2]])

**Not In-place Division**

In [63]:
torch_a

tensor([[8, 8],
        [8, 8]])

In [64]:
# Method 3
torch_a.div(torch_b)

tensor([[2, 2],
        [2, 2]])

In [65]:
torch_b

tensor([[4, 4],
        [4, 4]])

**In-place Division**

In [66]:
torch_a.div_(torch_b)

tensor([[2, 2],
        [2, 2]])

In [67]:
torch_a

tensor([[2, 2],
        [2, 2]])

___
### 1.5.7 Tensor Mean

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

mean_of_numbers = 1+2+3+4+5+6+7+8+9+10 / 10

mean_of_numbers = 5.5



In [68]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**Note: mean only support if dtype is float, not integers**

In [69]:
torch_numbers = torch.tensor(
    numbers, 
    dtype=torch.float32)

print(torch_numbers.shape)
torch_numbers

torch.Size([10])


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [70]:
torch_numbers.mean(dim=0)

tensor(5.5000)

**Modifiy the shape dimension**

In [71]:
torch_numbers = torch.tensor(
    [numbers, numbers], 
    dtype=torch.float32)

print(torch_numbers.shape)
torch_numbers

torch.Size([2, 10])


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [72]:
torch_numbers.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [73]:
torch_numbers.mean(dim=1)

tensor([5.5000, 5.5000])

### 1.5.8 Tensor Standard Deviation


In [74]:
torch_numbers.std(dim=1)

tensor([3.0277, 3.0277])

In [75]:
a = torch.ones(2, 2)
a * 4

tensor([[4., 4.],
        [4., 4.]])

In [76]:
torch.mul(a, 4)

tensor([[4., 4.],
        [4., 4.]])

In [77]:
b = torch.ones(2, 2) *2
b

tensor([[2., 2.],
        [2., 2.]])

In [78]:
a.matmul(b)

tensor([[4., 4.],
        [4., 4.]])